name: Rollback

on:
  workflow_dispatch:
#   inputs:
#     image_tag:
#       description: "Docker image tag to rollback to"
#       required: true
#       type: string

jobs:
  rollback:
    runs-on: self-hosted

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout HomeLab
        uses: actions/checkout@v5
        with:
          repository: SadNorth/HomeLab
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          clean: true
      
      - name: Get last known good version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "LAST_KNOWN_GOOD_TAG=$(gh variable get LAST_KNOWN_GOOD_TAG)" >> "$GITHUB_ENV"

#     - name: Download last known good version
#       env:
#         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         gh run download \
#           "$(cat run-id)" \
#           --repo SadNorth/devops-platform \
#           --name last_known_good \
#           --dir rollback-state
#       
#     - name: Read rollback version
#       run: |
#         echo "LAST_KNOWN_GOOD_TAG=$(cat rollback-state/last_known_good)" >> "$GITHUB_ENV"

#     - name: Debug workspace
#       run: |
#         echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
#         pwd
#         ls -la
#         find . -maxdepth 2 -type f | sort
          
      - name: Show rollback version
        run: |
          echo "Rolling back to: $LAST_KNOWN_GOOD_TAG"

      - name: Run Ansible rollback
        working-directory: ${{ github.workspace }}/ansible
        run: |
          ansible-playbook playbooks/rollback.yml \
            -e image_tag="$LAST_KNOWN_GOOD_TAG"