name: Rollback

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to rollback to"
        required: true
        type: string

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - name: Checkout HomeLab
        uses: actions/checkout@v5
        with:
          repository: SadNorth/HomeLab
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: HomeLab

      - name: Debug workspace
        run: |
          pwd
          find . -maxdepth 4 -type f | sort

      - name: Run Ansible rollback
        run: |
          cd HomeLab/ansible
          ansible-playbook playbooks/rollback.yml \
            -e image_tag=${{ inputs.image_tag }}